### ISSUE TITLE
TFT Data not up-to-date

### ISSUE THREAD

**Issue by un0btanium** [stelar7/lol-parser#9]
Hey,

like I already brought it up in another issue, the TFT data for 9.14.1b does not seem to reflect the changes made written in the patch notes. For example Ahri should deal 100/200/300 damage, but the values are still 100/175/250. Another example: Volibear attackspeed should be 0.55 but still shows as 0.65 like it did on patch 9.14.1a. 

I played a normal game of TFT to check if it updates and extracts the new data, but it sadly does not. So I wonder why that is. Is the data only on the server, not the client, because it was a micropatch/hotfixed in? And will it only be reflected on the client once the 9.15 patch drops? I will verify once it drops next week to make sure.

**Comment by stelar7** [comment]
It might be patched in with a separate file.. I'll take a look around later today.

**Comment by stelar7** [comment]
I'm unable to find anything from a quick look at the game files. if anyone finds it, feel free to create a new issue, and ill update the parser.

Closing this as this project is not really ment to support TFT especially.

**Comment by un0btanium** [comment]
Can confirm, that with the newest 9.15.0 patch, the TFT data is now up-to-date again.
edit: however, some of the data does not seem to be correct. Aatrox should have 700hp not 750 and his damage on his ability should also be lower.

**Comment by stelar7** [comment]
It seems like riot doesnt update the data files with all the info.. 🤷‍♂ 
(either that, or the patch notes lie?)

**Comment by un0btanium** [comment]
That's just unfortunate that they dont update it.
Nope, patchnotes are fine, even the ingame data shows the correct numbers and correlate with what was said in the patchnotes. Only the extracted data seems to be off in place :D

**Comment by un0btanium** [comment]
I ran the parser again and it seems the data is now correct. Not quite certain what exactly happened. Maybe it is me who cant use the parser correctly, who knows :D
